[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    { name = "Cyprien Lengagne", email = "cyprien.lengagne@epfl.ch" },
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi>=0.115.14",
    "uvicorn>=0.35.0",
    "networkx>=3.5",
    "numpy>=1.26.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "scipy>=1.16.0",
    "python-multipart>=0.0.20",
    "pandas>=2.1.3",
    "pillow>=11.3.0",
    "scikit-learn>=1.7.2",
    "fastapi-cache2>=0.2.2",
    "jinja2>=3.1.6",
    "aiosmtplib>=5.0.0",
    "mini-transit-simulation",
]

[project.optional-dependencies]
dev = [
    "dotenv>=0.9.9",
    "pytest>=8.4.1",
    "python-dotenv[cli]>=1.1.1",
]
test = [
    "pytest>=8.4.1",
]

[tool.codespell]
skip = 'uv.lock'

[tool.uv.sources]
mini-transit-simulation = { git = "https://github.com/EPFL-HOMES/mini-transit.git", rev="main" }
